### ISSUE TITLE
Remove references to LFN

### ISSUE THREAD

**Issue by jcwhitehead** [scarlehoff/pyHepGrid#22]
LFN support is already deprecated, let's just remove it?

**Comment by scarlehoff** [comment]
Is it really deprecated all across ARC?

Only 10 years after they said they were doing so, we should throw a removal party! :_)

**Comment by jcwhitehead** [comment]
They rebuilt the griduis and it looks like the LFC/LCG executables didn't make the cut...

**Comment by scarlehoff** [comment]
I can't help to wonder whether that is a feature or a bug x)

**Comment by jcwhitehead** [comment]
@DWalker487 says he's sorted this in his local branch (so probably not worth anyone else sorting this)

**Comment by marianheil** [comment]
There are still some references left to LFN (even though it is broken). It is mostly about cleaning up the code, not too urgent.
