### ISSUE TITLE
Add option to only print failed jobs

### ISSUE THREAD

**Issue by marianheil** [scarlehoff/pyHepGrid#30]
It would be nice to have an option to print only failed jobs on arc. Currently this is only possible through `arccat` on the specific job link.

**Comment by DWalker487** [comment]
See: https://github.com/scarlehoff/pyHepGrid/pull/32 - you can filter by job status if you've run -S beforehand to get the current statuses. Works as
```pyHepgrid man runcards/runcard.py -Bp -fl fail```
to select only failed jobs. You can select multiple statuses at the if you like :)
