### ISSUE TITLE
pyhepgrid init fails copying files

### ISSUE THREAD

**Issue by GandalfTheWhite2** [scarlehoff/pyHepGrid#35]
With the latest version I get the following errors when pyhepgrid init'ing:
(I have already ensured the grid directory is empty at the start, and the files are actually copied across - I wonder whether the script now tries copying with all the protocols, rather than with any one of the protocols?)

Copying file:/tmp/tmpim_4a1jc/Wm4j_HT2_7TeV+config_all.tar.gz to xroot:/se01.dur.scotgrid.ac.uk/dpm/dur.scotgrid.ac.uk/home/pheno/andersen/WJets_new/Wjets/input/Wm4j_HT2_7TeV+config_all.tar.gz
gfal-copy error: 17 (File exists) - Destination srm://se01.dur.scotgrid.ac.uk/dpm/dur.scotgrid.ac.uk/home/pheno/andersen/WJets_new/Wjets/input/Wm4j_HT2_7TeV+config_all.tar.gz exists and overwrite is not set
srm://se01.dur.scotgrid.ac.uk/dpm/dur.scotgrid.ac.uk/home/pheno/andersen/WJets_new/Wjets/input/Wm4j_HT2_7TeV+config_all.tar.gz        DELETED
Copying file:///tmp/tmpim_4a1jc/Wm4j_HT2_7TeV+config_all.tar.gz   [DONE]  after 2s                                       WARNING: Wm4j_HT2_7TeV+config_all.tar.gz could not be copied to the grid storage /for some reason/ after 2 attempt(s)
> Automatically trying again...
> Copying file:/tmp/tmpim_4a1jc/Wm4j_HT2_7TeV+config_all.tar.gz to xroot:/se01.dur.scotgrid.ac.uk/dpm/dur.scotgrid.ac.uk/home/pheno/andersen/WJets_new/Wjets/input/Wm4j_HT2_7TeV+config_all.tar.gz
gfal-copy error: 17 (File exists) - Destination srm://se01.dur.scotgrid.ac.uk/dpm/dur.scotgrid.ac.uk/home/pheno/andersen/WJets_new/Wjets/input/Wm4j_HT2_7TeV+config_all.tar.gz exists and overwrite is not set
srm://se01.dur.scotgrid.ac.uk/dpm/dur.scotgrid.ac.uk/home/pheno/andersen/WJets_new/Wjets/input/Wm4j_HT2_7TeV+config_all.tar.gz        DELETED
Copying file:///tmp/tmpim_4a1jc/Wm4j_HT2_7TeV+config_all.tar.gz   [DONE]  after 2s                                    
   WARNING: Wm4j_HT2_7TeV+config_all.tar.gz could not be copied to the grid storage /for some reason/ after 3 attempt(s)

**Comment by jcwhitehead** [comment]
@GandalfTheWhite2 The latest push should have fixed this - could you let me know if it works for you?

**Comment by GandalfTheWhite2** [comment]
It does! Thanks.
