### ISSUE TITLE
Runscripts are not python 2.4 compatible

### ISSUE THREAD

**Issue by scarlehoff** [scarlehoff/pyHepGrid#48]
I was having a quick look at the runscripts and noticed that they are using the `format` string method. This was backported to python 2 but only down to 2.6.

So either the comment

`try to keep this all python2.4 compatible. It may fail at some nodes otherwise :(`

is not true anymore or the scripts will fail because of that.

I would also refrain from using `print` without the `()`. I doubt you will find any node where python 3 is the default but you never know.

**Comment by jcwhitehead** [comment]
Thanks for this Juan, I was aware of some code that might not work in older versions but had forgotten about .format(). Do you remember which nodes had python version <2.7?

**Comment by scarlehoff** [comment]
Don't remember but it was some of the CentOS 5 (5.X, don't remember the X) which had python 2.4 as default. 

Closed with #49
