### ISSUE TITLE
Potentially aggressive use of grid commands

### ISSUE THREAD

**Issue by jcwhitehead** [scarlehoff/pyHepGrid#56]
@JBlack93 mentions in #55  that use of `gfal-ls` by `pyHepGrid` is perhaps suspected to be responsible for crashing the `gsiftp` service at the weekend.

We should keep on top of this as a potential issue: could you and @marianheil keep this issue updated with any information you receive?

**Comment by jcwhitehead** [comment]
@JBlack93 and @marianheil As part of this - could you ask anyone else in HEJ using `pyHepGrid` to `git pull` and update to the latest version?  That will enable `copy_log` by default (Marian added it to the HEJ header).

**Comment by JBlack93** [comment]
A few months on from the related fixes (https://github.com/scarlehoff/pyHepGrid/pull/50 + https://github.com/scarlehoff/pyHepGrid/pull/55) we have had no issues which can be related back to pyHepGrid itself. I think it is safe to close this issue now.
