### ISSUE TITLE
SRM has been retired

### ISSUE THREAD

**Issue by adamboutcher** [scarlehoff/pyHepGrid#61]
As part of an upgrade to grid storage, SRM is no long supported and has been retired please ensure that you don't use SRM at sites that no longer support it. gsiftp, xrootd and davs are prefered methods.

FYI Durham no longer supports it ;-)

**Comment by marianheil** [comment]
Just as a side node: running with `srm` wouldn't result in an error, but it is internally forwarded to `gsiftp`.

**Comment by adamboutcher** [comment]
> Just as a side node: running with `srm` wouldn't result in an error, but it is internally forwarded to `gsiftp`.

SRM currently internally makes gsiftp calls but this may not be true once SRM and "dpm-legacy" is retired fully as I'm sure the SRM endpoint wouldn't be listening at all. We haven't yet turned it off but plan to very soon. 

We will test and give feedback but I'd suggest to bin off any SRM calls in favour for xroot or gsiftp which would give cleaner code and be more portable. outside of Durham.

**Comment by jcwhitehead** [comment]
Hi @adamboutcher - could you advise on whether `dav` and `davs` are aliases of one another, or are distinct protocols?

**Comment by adamboutcher** [comment]
They are alias of the same thing.

**Comment by jcwhitehead** [comment]
SRM now removed.  Thanks for the heads-up!
