### ISSUE TITLE
Fix or remove broken function

### ISSUE THREAD

**Issue by marianheil** [scarlehoff/pyHepGrid#70]
Follow up on f7ba0fcc27c14ec314051712a9ffc65e4db1fcb6 

https://github.com/scarlehoff/pyHepGrid/blob/ec9df4b2ecf3f496678c05d4a2b1371b564bc6ec/src/pyHepGrid/src/runcard_parsing.py#L128-L141

Is broken (`runcard_linecode` is undefined) and never called. @jcwhitehead do you know what's going on? Can we remove the function?

**Comment by jcwhitehead** [comment]
Hangover from previous version - fine to remove
