### ISSUE TITLE
flake8 too restrictive?

### ISSUE THREAD

**Issue by scarlehoff** [scarlehoff/pyHepGrid#77]
A change in the readme made flake8 to fail... and it was passing a month ago.

I guess there was _some_ update for flake that introduced the problem but I don't think the passing (or not) of the test should rely on external tools updating the way we like it...

**Comment by jcwhitehead** [comment]
Looking at these, I'm surprised flake's tests ever passed!

If flake keeps noticing new problems and they start to seem superficial or trivial, I'd support relaxing its settings, but these look like good things to have had flagged up.  Not sure when we'd have noticed some of them otherwise.

**Comment by marianheil** [comment]
So its [this CI](https://github.com/scarlehoff/pyHepGrid/runs/740165511) that failed, compared to [this](https://github.com/scarlehoff/pyHepGrid/runs/642201641).

Seems like `flake8` updated to 3.8.2 which now uses [new errors](https://github.com/PyCQA/flake8/commit/76eeccad89ac83d7049ec7ebb10776609f7a103d) from `pyflakes` 2.2.0 and also `pycodestyle` updated to 2.6.0 which added the [new warning E225](https://pycodestyle.pycqa.org/en/latest/developer.html#a1-2020-04-23).

For `pycodestyle` using `Black` (e.g. #71) might do the trick. `pyflakes` on the other hand catches (potential) errors. We should keep that up to date. With roughly [one release per year](https://github.com/PyCQA/pyflakes/blob/master/NEWS.rst) for `pyflakes` that seems manageable.

**Comment by scarlehoff** [comment]
> With roughly one release per year for pyflakes that seems manageable.

Mm, that looks acceptable I guess.

**Comment by scarlehoff** [comment]
> Looking at these, I'm surprised flake's tests ever passed!

Indeed, thanks for the fix!
